name: $(BuildDefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)
pool: Hosted Ubuntu 1604
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: "3.7"
- script: |
    python -m pip install --upgrade pip
    python -m pip install pylint pytest pytest-cov pytest-azurepipelines
  displayName: Install tools
- script: pip install -e .
  displayName: Install package
- script: pylint --disable=C,W,R victoria_pbi
  displayName: Lint Python package
- script: pytest tests/ --cov victoria_pbi --cov-report html
  displayName: Test Python package
- task: SonarCloudPrepare@1
  displayName: Prepare analysis on SonarCloud
  inputs:
    SonarCloud: SonarCloud connection
    organization: glasswall-cloud-key-a42w31
    projectKey: $(Build.Repository.Name)
    projectName: $(Build.Repository.Name)
    extraProperties: |
      "sonar.python.coverage.reportPaths=$(Agent.BuildDirectory)/coverage.xml"
      "sonar.python.xunit.reportPath=$(Agent.BuildDirectory)/test-output.xml"
- task: SonarCloudAnalyze@1
  displayName: Run code analysis on SonarCloud